// Generated by tools/gen_ui154_layout.py. Do not edit by hand.
#pragma once
#include <stddef.h>
#include <stdint.h>

typedef enum { UI154_ALIGN_LEFT = 0, UI154_ALIGN_CENTER = 1, UI154_ALIGN_RIGHT = 2 } ui154_align_t;
typedef struct {
  const char *page_id;
  const char *field_id;
  const char *default_text;
  int16_t x, y, width, height;
  uint8_t size, line_height, max_lines, align;
  uint16_t weight;
} ui154_layout_field_t;

const ui154_layout_field_t *ui154_layout_fields(size_t *count);
const ui154_layout_field_t *ui154_layout_find(const char *page_id, const char *field_id);
const char *ui154_layout_sha256(void);
