#!/usr/bin/env python3
"""Generate the firmware-side text layout table from the approved UI JSON."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


DEFAULT_LAYOUT = Path(
    r"D:\OPENOP\Luoye_UI_Layout_Editor\final_layout_r2\luoye_ui_layout_FINAL.json"
)


def c_string(value: str) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def main() -> None:
    project = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", default=str(DEFAULT_LAYOUT))
    parser.add_argument("--header", default=str(project / "main" / "ui154_layout_generated.h"))
    parser.add_argument("--source", default=str(project / "main" / "ui154_layout_generated.c"))
    args = parser.parse_args()

    layout_path = Path(args.layout)
    raw = layout_path.read_bytes()
    data = json.loads(raw.decode("utf-8-sig"))
    if data.get("schema") != "luoye-ui-layout/v3" or data.get("canvas") != [200, 200]:
        raise SystemExit("unsupported layout schema or canvas")
    if len(data.get("pages", [])) != 23:
        raise SystemExit("the approved firmware layout must contain 23 pages")

    rows = []
    for page in data["pages"]:
        for field in page["fields"]:
            if field.get("type", "text") == "image":
                continue
            x, y = int(round(field["x"])), int(round(field["y"]))
            width = int(round(field["width"]))
            size = int(round(field["size"]))
            max_lines = int(field.get("maxLines", 1))
            line_height = int(round(field.get("lineHeight", size * 1.25)))
            height = int(round(field.get("height", max(size, line_height * max_lines))))
            align = {"left": 0, "center": 1, "right": 2}.get(field.get("align", "left"), 0)
            rows.append(
                (page["id"], field["id"], field.get("text", ""), x, y, width,
                 height, size, line_height, max_lines, align, int(field.get("weight", 400)))
            )

    digest = hashlib.sha256(raw).hexdigest()
    header = Path(args.header)
    source = Path(args.source)
    header.write_text(
        "// Generated by tools/gen_ui154_layout.py. Do not edit by hand.\n"
        "#pragma once\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "typedef enum { UI154_ALIGN_LEFT = 0, UI154_ALIGN_CENTER = 1, UI154_ALIGN_RIGHT = 2 } ui154_align_t;\n"
        "typedef struct {\n"
        "  const char *page_id;\n"
        "  const char *field_id;\n"
        "  const char *default_text;\n"
        "  int16_t x, y, width, height;\n"
        "  uint8_t size, line_height, max_lines, align;\n"
        "  uint16_t weight;\n"
        "} ui154_layout_field_t;\n\n"
        "const ui154_layout_field_t *ui154_layout_fields(size_t *count);\n"
        "const ui154_layout_field_t *ui154_layout_find(const char *page_id, const char *field_id);\n"
        "const char *ui154_layout_sha256(void);\n",
        encoding="utf-8",
    )

    lines = [
        "// Generated by tools/gen_ui154_layout.py. Do not edit by hand.",
        '#include "ui154_layout_generated.h"',
        "#include <string.h>",
        "",
        f'static const char s_layout_sha256[] = "{digest}";',
        "static const ui154_layout_field_t s_fields[] = {",
    ]
    for row in rows:
        page, field, text, x, y, width, height, size, line_height, max_lines, align, weight = row
        lines.append(
            f"  {{{c_string(page)}, {c_string(field)}, {c_string(text)}, "
            f"{x}, {y}, {width}, {height}, {size}, {line_height}, {max_lines}, {align}, {weight}}},"
        )
    lines.extend(
        [
            "};",
            "",
            "const ui154_layout_field_t *ui154_layout_fields(size_t *count) {",
            "  if (count) *count = sizeof(s_fields) / sizeof(s_fields[0]);",
            "  return s_fields;",
            "}",
            "",
            "const ui154_layout_field_t *ui154_layout_find(const char *page_id, const char *field_id) {",
            "  if (!page_id || !field_id) return NULL;",
            "  for (size_t i = 0; i < sizeof(s_fields) / sizeof(s_fields[0]); ++i) {",
            "    if (strcmp(s_fields[i].page_id, page_id) == 0 && strcmp(s_fields[i].field_id, field_id) == 0)",
            "      return &s_fields[i];",
            "  }",
            "  return NULL;",
            "}",
            "",
            "const char *ui154_layout_sha256(void) { return s_layout_sha256; }",
            "",
        ]
    )
    source.write_text("\n".join(lines), encoding="utf-8")
    print(f"OK: {len(rows)} text fields, layout={digest}")
    print(f"Header: {header}")
    print(f"Source: {source}")


if __name__ == "__main__":
    main()
